# Generated by Django 5.2.7 on 2025-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy', models.FloatField(help_text='Total energy in kWh')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
