# Generated by Django 5.2.7 on 2025-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(default=0.0)),
                ('current', models.FloatField(default=0.0)),
                ('power', models.FloatField(default=0.0)),
                ('total_energy_kwh', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EnergyReading',
        ),
    ]
