# Generated by Django 5.2.7 on 2025-11-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_meter_delete_energyreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='current',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='power',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='voltage',
        ),
    ]
