# Generated by Django 5.1.6 on 2025-11-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_meter_current_remove_meter_power_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['meter_id'], 'verbose_name': 'Energy Meter', 'verbose_name_plural': 'Energy Meters'},
        ),
        migrations.AddField(
            model_name='meter',
            name='current_power_w',
            field=models.FloatField(default=0.0, help_text='Current power in watts'),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_id',
            field=models.CharField(default='main', help_text='Unique identifier for the meter', max_length=50, unique=True),
        ),
    ]
