# Generated by Django 5.1.6 on 2025-11-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_meter_options_meter_current_power_w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='total_energy_kwh',
        ),
        migrations.AddField(
            model_name='meter',
            name='total_energy_wh',
            field=models.BigIntegerField(default=0, help_text='Total energy in watt-hours (integer)'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='current_power_w',
            field=models.IntegerField(default=0, help_text='Current power in watts (integer)'),
        ),
    ]
