# Generated by Django 5.1.6 on 2025-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_remove_meter_total_energy_kwh_meter_total_energy_wh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(default='solar', help_text='Unique identifier for the solar meter', max_length=50, unique=True)),
                ('total_energy_wh', models.BigIntegerField(default=0, help_text='Total solar energy in watt-hours (integer)')),
                ('current_power_w', models.IntegerField(default=0, help_text='Current solar power in watts (integer)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Solar Energy Meter',
                'verbose_name_plural': 'Solar Energy Meters',
                'ordering': ['meter_id'],
            },
        ),
    ]
