# Generated by Django 5.2.7 on 2025-10-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmeter',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='virtualmeter',
            name='peak_power_w',
            field=models.FloatField(default=0.0),
        ),
    ]
