# Generated by Django 5.2.7 on 2025-10-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_remove_virtualmeter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='VirtualMeter',
        ),
    ]
